### ISSUE TITLE
Creating signed_yearfrac

### ISSUE THREAD

**Issue by n-kishaloy** [AnatolyBuga/yearfrac#1]
Hi,

Firstly, great job in creating this extremely useful utility. I was hoping that you would add a `signed_yearfrac` to allow for negative value of yearfrac. 

I understand that MS Excel only provides the absolute value and not signed based on whether the first date is more or less than the second date, however, a signed yearfrac can be extremely useful when doing simulations over a range of dates. It would only require creating a `fn signed_diff_dts` by removing the `abs()` in ` (start-end).num_days().abs() as f64` and `fn diff_dts` can simply be the `abs()` version of it. 

Kishaloy.

**Comment by AnatolyBuga** [comment]
@n-kishaloy , Glad you found the library useful! Sure, it sounds like a nice and simple addition to the library. I will try to add and test that over the weekend and release an update then. 
And btw if you can think of any other improvements feel free to reach out/submit pull rqsts!
Regards,

**Comment by n-kishaloy** [comment]
Also, looking at the code it seems that the `abs()` is only applied to the Act versions and not the days360 version creating a kinda inconsistency. But have not checked in details just was going through the code. Maybe you can check same as well. In any case, having both signed and absolute or only one which is signed are equally good.

**Comment by AnatolyBuga** [comment]
https://github.com/AnatolyBug/yearfrac/pull/2

added^
